package fileformat

import (
	"bufio"
	"bytes"
	"strings"

	"gopkg.in/yaml.v3"
)

// FileKind identifies the type of doc file.
type FileKind string

const (
	KindIndex   FileKind = "index"
	KindSection FileKind = "section"
	KindMethod  FileKind = "method"
	KindConcept FileKind = "concept"
)

// Frontmatter holds the YAML frontmatter for all doc files.
type Frontmatter struct {
	ID                 string   `yaml:"id"`
	Kind               FileKind `yaml:"kind"`
	Section            string   `yaml:"section,omitempty"`
	Symbol             string   `yaml:"symbol,omitempty"`
	VersionAdded       string   `yaml:"version_added,omitempty"`
	VersionLastChanged string   `yaml:"version_last_changed,omitempty"`
	LastUpdated        string   `yaml:"last_updated,omitempty"`
	Fingerprint        string   `yaml:"fingerprint,omitempty"`
	AutoGenerated      bool     `yaml:"auto_generated"`
	Related            []string `yaml:"related,omitempty"`
	Gotchas            []string `yaml:"gotchas,omitempty"`
	Tags               []string `yaml:"tags,omitempty"`
	Complexity         string   `yaml:"complexity,omitempty"`
}

// DocFile represents a parsed doc file with frontmatter and body.
type DocFile struct {
	Frontmatter Frontmatter
	Body        string
}

// ParseDocFile parses a doc file into frontmatter and body.
func ParseDocFile(content []byte) (*DocFile, error) {
	scanner := bufio.NewScanner(bytes.NewReader(content))

	// Look for opening ---
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return &DocFile{Body: string(content)}, nil
	}

	// Read frontmatter lines
	var fmLines []string
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "---" {
			break
		}
		fmLines = append(fmLines, line)
	}

	var fm Frontmatter
	if err := yaml.Unmarshal([]byte(strings.Join(fmLines, "\n")), &fm); err != nil {
		return nil, err
	}

	// Rest is body — collect remaining lines from scanner
	var bodyLines []string
	for scanner.Scan() {
		bodyLines = append(bodyLines, scanner.Text())
	}

	body := strings.Join(bodyLines, "\n")
	// Preserve trailing newline if original content had one
	if len(content) > 0 && content[len(content)-1] == '\n' && !strings.HasSuffix(body, "\n") {
		body += "\n"
	}

	return &DocFile{
		Frontmatter: fm,
		Body:        body,
	}, nil
}

// RenderDocFile serializes a DocFile back to bytes with YAML frontmatter.
func RenderDocFile(doc *DocFile) ([]byte, error) {
	fmBytes, err := yaml.Marshal(&doc.Frontmatter)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	buf.WriteString("---\n")
	buf.Write(fmBytes)
	buf.WriteString("---\n")
	buf.WriteString(doc.Body)
	return buf.Bytes(), nil
}
