package fileformat_test

import (
	"testing"

	"github.com/morethancoder/srcmap/pkg/fileformat"
)

func TestFrontmatterRoundtrip(t *testing.T) {
	original := &fileformat.DocFile{
		Frontmatter: fileformat.Frontmatter{
			ID:            "telegram.sendMessage",
			Kind:          fileformat.KindMethod,
			Section:       "bot-api",
			Symbol:        "sendMessage",
			AutoGenerated: true,
			Related:       []string{"editMessageText", "copyMessage"},
			Tags:          []string{"messaging"},
			Complexity:    "medium",
		},
		Body: "\n# sendMessage\n\nSends a message to a chat.\n",
	}

	rendered, err := fileformat.RenderDocFile(original)
	if err != nil {
		t.Fatalf("render: %v", err)
	}

	parsed, err := fileformat.ParseDocFile(rendered)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	if parsed.Frontmatter.ID != original.Frontmatter.ID {
		t.Errorf("id: got %q, want %q", parsed.Frontmatter.ID, original.Frontmatter.ID)
	}
	if parsed.Frontmatter.Kind != original.Frontmatter.Kind {
		t.Errorf("kind: got %q, want %q", parsed.Frontmatter.Kind, original.Frontmatter.Kind)
	}
	if parsed.Frontmatter.Section != original.Frontmatter.Section {
		t.Errorf("section: got %q, want %q", parsed.Frontmatter.Section, original.Frontmatter.Section)
	}
	if len(parsed.Frontmatter.Related) != len(original.Frontmatter.Related) {
		t.Errorf("related count: got %d, want %d", len(parsed.Frontmatter.Related), len(original.Frontmatter.Related))
	}
	if parsed.Body != original.Body {
		t.Errorf("body: got %q, want %q", parsed.Body, original.Body)
	}
}

func TestParseNoFrontmatter(t *testing.T) {
	content := []byte("# Just a heading\n\nSome body text.\n")
	doc, err := fileformat.ParseDocFile(content)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if doc.Frontmatter.ID != "" {
		t.Errorf("expected empty frontmatter ID, got %q", doc.Frontmatter.ID)
	}
	if doc.Body != string(content) {
		t.Errorf("body should be full content when no frontmatter")
	}
}
