package fileformat

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

// HierarchyBuilder creates and manages the doc file hierarchy for a source.
type HierarchyBuilder struct {
	BaseDir string // .srcmap/docs/{source}/
}

// NewHierarchyBuilder creates a builder for the given source's docs directory.
func NewHierarchyBuilder(srcmapDir, sourceName string) *HierarchyBuilder {
	return &HierarchyBuilder{
		BaseDir: filepath.Join(srcmapDir, "docs", sanitizeName(sourceName)),
	}
}

// EnsureStructure creates the base directory structure.
func (h *HierarchyBuilder) EnsureStructure() error {
	return os.MkdirAll(h.BaseDir, 0o755)
}

// WriteIndex writes or updates the root index.md file.
func (h *HierarchyBuilder) WriteIndex(sections []SectionSummary) error {
	fm := Frontmatter{
		ID:            "index",
		Kind:          KindIndex,
		AutoGenerated: true,
		LastUpdated:   Now(),
	}

	var body strings.Builder
	body.WriteString("\n# Index\n\n")
	for _, s := range sections {
		body.WriteString(fmt.Sprintf("- **[%s](%s/section.md)** — %s\n", s.Name, sanitizeName(s.Name), s.Description))
	}

	return h.writeDocFile(filepath.Join(h.BaseDir, "index.md"), &DocFile{
		Frontmatter: fm,
		Body:        body.String(),
	})
}

// WriteSection writes or updates a section.md file.
func (h *HierarchyBuilder) WriteSection(sectionName string, methods []MethodSummary) error {
	sectionDir := filepath.Join(h.BaseDir, sanitizeName(sectionName))
	if err := os.MkdirAll(sectionDir, 0o755); err != nil {
		return err
	}

	fm := Frontmatter{
		ID:            sectionName,
		Kind:          KindSection,
		Section:       sectionName,
		AutoGenerated: true,
		LastUpdated:   Now(),
	}

	var body strings.Builder
	body.WriteString(fmt.Sprintf("\n# %s\n\n", sectionName))
	for _, m := range methods {
		// Route each entry to the subdirectory its file actually lives in.
		// Kind "concept" → concepts/, anything else → methods/ (default).
		subdir := "methods"
		if m.Kind == "concept" {
			subdir = "concepts"
		}
		body.WriteString(fmt.Sprintf("- **[%s](%s/%s.md)** — %s\n", m.Name, subdir, sanitizeName(m.Name), m.Summary))
	}

	return h.writeDocFile(filepath.Join(sectionDir, "section.md"), &DocFile{
		Frontmatter: fm,
		Body:        body.String(),
	})
}

// WriteMethod writes or updates a method.md file.
func (h *HierarchyBuilder) WriteMethod(sectionName string, method *DocFile) error {
	dir := filepath.Join(h.BaseDir, sanitizeName(sectionName), "methods")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	name := sanitizeName(method.Frontmatter.Symbol)
	if name == "" {
		name = sanitizeName(method.Frontmatter.ID)
	}
	return h.writeDocFile(filepath.Join(dir, name+".md"), method)
}

// WriteConcept writes or updates a concept.md file.
func (h *HierarchyBuilder) WriteConcept(sectionName string, concept *DocFile) error {
	dir := filepath.Join(h.BaseDir, sanitizeName(sectionName), "concepts")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	name := sanitizeName(concept.Frontmatter.ID)
	return h.writeDocFile(filepath.Join(dir, name+".md"), concept)
}

// AppendGotcha adds a gotcha entry to gotchas.md.
func (h *HierarchyBuilder) AppendGotcha(id, content string) error {
	path := filepath.Join(h.BaseDir, "gotchas.md")

	existing, _ := os.ReadFile(path)
	body := string(existing)

	// Check if this gotcha ID already exists
	if strings.Contains(body, fmt.Sprintf("<!-- gotcha:%s -->", id)) {
		return nil // already present
	}

	if body == "" {
		body = "# Gotchas\n\n"
	}

	body += fmt.Sprintf("<!-- gotcha:%s -->\n## %s\n\n%s\n\n", id, id, content)

	return os.WriteFile(path, []byte(body), 0o644)
}

// AppendChangelog adds an entry to CHANGELOG.md.
func (h *HierarchyBuilder) AppendChangelog(entry string) error {
	path := filepath.Join(h.BaseDir, "CHANGELOG.md")

	existing, _ := os.ReadFile(path)
	body := string(existing)

	if body == "" {
		body = "# Changelog\n\n"
	}

	timestamp := time.Now().UTC().Format("2006-01-02 15:04")
	body += fmt.Sprintf("## %s\n\n%s\n\n", timestamp, entry)

	return os.WriteFile(path, []byte(body), 0o644)
}

// writeDocFile writes a DocFile, preserving any <!-- custom --> blocks from an existing file.
func (h *HierarchyBuilder) writeDocFile(path string, doc *DocFile) error {
	// Check for existing custom blocks
	if existing, err := os.ReadFile(path); err == nil {
		customBlocks := extractCustomBlocks(string(existing))
		if len(customBlocks) > 0 {
			doc.Body = mergeCustomBlocks(doc.Body, customBlocks)
		}
	}

	data, err := RenderDocFile(doc)
	if err != nil {
		return fmt.Errorf("rendering doc file: %w", err)
	}

	return os.WriteFile(path, data, 0o644)
}

// SectionSummary holds summary info for the index.
type SectionSummary struct {
	Name        string
	Description string
}

// MethodSummary holds summary info for a section listing.
type MethodSummary struct {
	Name    string
	Summary string
	// Kind is "method" or "concept" — decides whether the section.md link
	// points into methods/ or concepts/. Empty defaults to "method".
	Kind string
}

var customBlockRe = regexp.MustCompile(`(?s)<!-- custom -->(.*?)<!-- /custom -->`)

func extractCustomBlocks(content string) []string {
	matches := customBlockRe.FindAllStringSubmatch(content, -1)
	var blocks []string
	for _, m := range matches {
		blocks = append(blocks, m[0])
	}
	return blocks
}

func mergeCustomBlocks(newBody string, customBlocks []string) string {
	for _, block := range customBlocks {
		if !strings.Contains(newBody, block) {
			newBody += "\n" + block + "\n"
		}
	}
	return newBody
}

func sanitizeName(name string) string {
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, " ", "-")
	name = strings.ReplaceAll(name, "/", "-")
	name = strings.ReplaceAll(name, ".", "-")
	// Remove anything that's not alphanumeric, dash, or underscore
	re := regexp.MustCompile(`[^a-z0-9\-_]`)
	return re.ReplaceAllString(name, "")
}

func Now() string {
	return time.Now().UTC().Format(time.RFC3339)
}
