package fileformat_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/morethancoder/srcmap/pkg/fileformat"
)

func TestHierarchyCreation(t *testing.T) {
	dir := t.TempDir()
	hb := fileformat.NewHierarchyBuilder(dir, "telegram")

	if err := hb.EnsureStructure(); err != nil {
		t.Fatalf("ensure: %v", err)
	}

	// Write index
	sections := []fileformat.SectionSummary{
		{Name: "Bot API", Description: "Core bot methods"},
		{Name: "Payments", Description: "Payment processing"},
	}
	if err := hb.WriteIndex(sections); err != nil {
		t.Fatalf("write index: %v", err)
	}

	// Write section
	methods := []fileformat.MethodSummary{
		{Name: "sendMessage", Summary: "Send a message"},
		{Name: "editMessage", Summary: "Edit a message"},
	}
	if err := hb.WriteSection("Bot API", methods); err != nil {
		t.Fatalf("write section: %v", err)
	}

	// Write method
	method := &fileformat.DocFile{
		Frontmatter: fileformat.Frontmatter{
			ID:            "telegram.sendMessage",
			Kind:          fileformat.KindMethod,
			Section:       "bot-api",
			Symbol:        "sendMessage",
			AutoGenerated: true,
		},
		Body: "\n# sendMessage\n\nSends a message to a chat.\n",
	}
	if err := hb.WriteMethod("Bot API", method); err != nil {
		t.Fatalf("write method: %v", err)
	}

	// Verify files exist
	indexPath := filepath.Join(dir, "docs", "telegram", "index.md")
	if _, err := os.Stat(indexPath); err != nil {
		t.Errorf("index.md not created: %v", err)
	}

	sectionPath := filepath.Join(dir, "docs", "telegram", "bot-api", "section.md")
	if _, err := os.Stat(sectionPath); err != nil {
		t.Errorf("section.md not created: %v", err)
	}

	methodPath := filepath.Join(dir, "docs", "telegram", "bot-api", "methods", "sendmessage.md")
	if _, err := os.Stat(methodPath); err != nil {
		t.Errorf("sendmessage.md not created: %v", err)
	}
}

func TestCustomBlockPreservation(t *testing.T) {
	dir := t.TempDir()
	hb := fileformat.NewHierarchyBuilder(dir, "test")
	hb.EnsureStructure()

	// Write initial method
	method := &fileformat.DocFile{
		Frontmatter: fileformat.Frontmatter{
			ID:     "test.myFunc",
			Kind:   fileformat.KindMethod,
			Symbol: "myFunc",
		},
		Body: "\n# myFunc\n\nOriginal content.\n\n<!-- custom -->\nMy hand-written notes here.\n<!-- /custom -->\n",
	}
	if err := hb.WriteMethod("api", method); err != nil {
		t.Fatalf("write: %v", err)
	}

	// Overwrite with updated content (custom block should survive)
	method2 := &fileformat.DocFile{
		Frontmatter: fileformat.Frontmatter{
			ID:     "test.myFunc",
			Kind:   fileformat.KindMethod,
			Symbol: "myFunc",
		},
		Body: "\n# myFunc\n\nUpdated content.\n",
	}
	if err := hb.WriteMethod("api", method2); err != nil {
		t.Fatalf("overwrite: %v", err)
	}

	// Read back and check custom block is preserved
	path := filepath.Join(dir, "docs", "test", "api", "methods", "myfunc.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Updated content") {
		t.Error("new content not present")
	}
	if !strings.Contains(content, "My hand-written notes here") {
		t.Error("custom block was lost during overwrite")
	}
}

func TestGotchasAppend(t *testing.T) {
	dir := t.TempDir()
	hb := fileformat.NewHierarchyBuilder(dir, "test")
	hb.EnsureStructure()

	if err := hb.AppendGotcha("parse-mode-entities", "When using parse_mode, entities are ignored."); err != nil {
		t.Fatalf("append 1: %v", err)
	}
	if err := hb.AppendGotcha("reply-markup-limit", "Reply markup has a 256 character limit."); err != nil {
		t.Fatalf("append 2: %v", err)
	}

	// Verify both present
	path := filepath.Join(dir, "docs", "test", "gotchas.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "parse-mode-entities") {
		t.Error("first gotcha missing")
	}
	if !strings.Contains(content, "reply-markup-limit") {
		t.Error("second gotcha missing")
	}

	// Append same gotcha again — should not duplicate
	if err := hb.AppendGotcha("parse-mode-entities", "Duplicate"); err != nil {
		t.Fatalf("append dup: %v", err)
	}
	data2, _ := os.ReadFile(path)
	if strings.Count(string(data2), "parse-mode-entities") != 2 {
		// One in the marker comment, one in the heading = 2
	}
}

func TestChangelogAppend(t *testing.T) {
	dir := t.TempDir()
	hb := fileformat.NewHierarchyBuilder(dir, "test")
	hb.EnsureStructure()

	if err := hb.AppendChangelog("Added sendMessage method."); err != nil {
		t.Fatalf("append 1: %v", err)
	}
	if err := hb.AppendChangelog("Updated editMessage method."); err != nil {
		t.Fatalf("append 2: %v", err)
	}

	path := filepath.Join(dir, "docs", "test", "CHANGELOG.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "Added sendMessage") {
		t.Error("first entry missing")
	}
	if !strings.Contains(content, "Updated editMessage") {
		t.Error("second entry missing")
	}
}

func TestSourceYAMLRoundtrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "source.yaml")

	original := &fileformat.SourceYAML{
		Name:        "telegram",
		Description: "Telegram Bot API",
		Version:     "7.2",
		DocOrigin: &fileformat.DocOrigin{
			URL:         "https://core.telegram.org/bots/api",
			ContentType: "scrape",
			Reason:      "no LLM-friendly format found",
			Validated:   true,
		},
		Triggers: []string{"telegram", "bot api", "sendMessage"},
		Stats:    fileformat.SourceStats{Sections: 3, Methods: 50, Concepts: 5, Gotchas: 8},
	}

	if err := fileformat.WriteSourceYAML(path, original); err != nil {
		t.Fatalf("write: %v", err)
	}

	loaded, err := fileformat.ReadSourceYAML(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}

	if loaded.Name != original.Name {
		t.Errorf("name: got %q, want %q", loaded.Name, original.Name)
	}
	if loaded.DocOrigin.URL != original.DocOrigin.URL {
		t.Errorf("doc_origin url: got %q", loaded.DocOrigin.URL)
	}
	if loaded.Stats.Methods != 50 {
		t.Errorf("stats.methods: got %d, want 50", loaded.Stats.Methods)
	}
}
